### ISSUE TITLE
Redacting files with spaces in the path

### ISSUE THREAD

**Issue by nkrabben** [BitCurator/bitcurator-access-redaction#7]
I'm having trouble redacting files with a space in the file path. I think it has to do with the way that the config file is parsed.
https://github.com/BitCurator/bitcurator-access-redaction/blob/6b4587d1c7f7d5556246ad92b591b93a7913b02b/libredact/libredact/config.py#L33

I've tried the following
* quoting the entire path - parse error, Cannot parse '%s'
* escaping the space with \ - re error, bogus escape 
* escaping the space with double\ - parse error, Cannot parse '%s'
* using regex for space: %s - works
* using wildcard: * - works

I don't think that you can mix regex and wildcards, so if you either need to use
```
FILE_NAME_MATCH C:\Users\.+\AppData\Local\Google\Chrome\User%sData\Default\ SCRUB
```
or
```
FILE_NAME_MATCH C:\Users\*\AppData\Local\Google\Chrome\User*Data\Default\ SCRUB
```

**Comment by kamwoods** [comment]
Noted. Marked for fix / improved parsing.

**Comment by kamwoods** [comment]
Closing as this repository is now end-of-life.
